---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaling-deployment
  labels:
    type: proxy
spec:
  replicas: 2
  selector:
    type: proxy
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: proxy
    spec:
      containers:
        - name: my-tomcat
          image: tomcat
      resources:
        requests:
          cpu: 20Gi
        limits:
          cpu: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    type: proxy
spec:
  type: LoadBalancer
  selector:
    type: proxy
  ports:
    - targetPort: 8080
      port: 9090
      nodePort: 30019


