---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  labels:
    type: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: proxy
    spec:
      containers:
        - name: mytomcat
          image: tomcat
          ports:
            - containerPort: 8080
              hostPort: 7070
...
