---
apiVersion: v1
kind: Service 
metadata:
  name: add-port
  labels:
    name: chandu
    type: prototype
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 8080
      nodePort: 30008
  selector:
    author: chandu
    app: proxy
...
