---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    name: chandu
    type: webserver
spec:
  containers:
    - name: apache
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 9090
      resources:
        requests:
          memory: 64Mi
          cpu: 200m
        limits:
           memory: 130Mi
           cpu: 500m
...
