---
apiVersion: v1
kind: Secret
metadata:
  name: database-postgres
  labels:
    type: proxy
    name: chandu
type: Opaque
stringData:
  a: chandu
  b: chandu
  c: chandu
  d: chandu

----------------------------------------------------------
configMap : stores insensitive data                                         [ ETCD : which stores cluster information ] 
secrets :   stores sensitive data

difference b/w them :
                        configMap stores insensitive data in a plain text format in etcd everyone can access it  , even it got compromised also no issue 

                        secrets stores the sensitive data and encryted at REST in etcd, which can bot be compromised , who has encrytpion key they can only access 
                        we should use the least permission using the RBACK so only limited can access it
                        kubernetes give encrytion for the secundary levl secirty need to se the RBACK
---------------------------------------------------------------------------------------------------------------
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: test
data:
  chandu: testing 






