---
apiVersion: v1
kind: Service
metadata:
  name: temporary-data-store
  labels:
    name: chandu
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 9090
  selector:
    name: chandu
...
