---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: chandu
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30007
  selector:
    name: chandu
...
