---
apiVersion: v1
kind: Service
metadata:
  name: voting
  labels:
    name: chandu
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    name: chandu 
...
