---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace1

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-pod
  namespace: namespace1
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-rolebinding
  namespace: namespace1
subjects:
  - kind: User
    name: chandu
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-pod
  apiGroup: rbac.authorization.k8s.io
