---
apiVersion: v1
kind: Pod
metadata:
  name: afinity-prototype
  labels:
    name: chandu
    type: proxy
spec:
  containers:
    - name: database
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: chandu
      ports:
        - containerPort: 3306
          hostPort: 9090
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: slave3
              operator: In
              values:
                - chandu
